# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6945e91dea8be1b2f9e19074c708d6cc290635b6d66445ebcbe0a499252341fb3c30516a483be4fa6490bd2335ac54b16351b2f2550f48f730ab8c59d0e7f5cd
  FACEBOOK_APP_ID: "232349067302447"
  FACEBOOK_APP_SECRET: "1fdf6fdf346b4fbef416cc838ce04d0f"
  GOOGLE_APP_ID: "896454387297-9v2hq4fk49c93jpqhu0ftuspo4kscu0b.apps.googleusercontent.com"
  GOOGLE_APP_SECRET: "8BHJnU8Z5ioMFnQWzTf5_ZVU"
test:
  secret_key_base: d1a275994420f0bceb58156551df2e38a7503860c23a5da7a4ac99f98f2a4e01dc19dcbe7ecfa83d0ce583873336061e4c02db7459adbd4296e7016e9d9d6c1c
  FACEBOOK_APP_ID: "232349067302447"
  FACEBOOK_APP_SECRET: "1fdf6fdf346b4fbef416cc838ce04d0f"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_APP_ID: "232349067302447"
  FACEBOOK_APP_SECRET: "1fdf6fdf346b4fbef416cc838ce04d0f"
